### ISSUE TITLE
Issue in Grid sorting, null values not handled in sortMultiple function (when sortMode=multiple)

### ISSUE THREAD

**Issue by yashkk3640** [primefaces/primereact#2157]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**
Please fork the codesandbox below and create a case demonstrating your bug report. Issues without a codesandbox have much less possibility to be reviewed.

https://codesandbox.io/s/wonderful-lederberg-2cvgy?file=/src/demo/DataTableSortDemo.js
![image](https://user-images.githubusercontent.com/53908595/124276879-00b3e680-db62-11eb-930b-356c8d87b28d.png)

**Current behavior**
Sorting not working properly when sortMode=multiple

**Expected behavior**
It's should be sort properly all types of data don't matter user sorting single or multiple sorts when sortMode=multiple

* **PrimeReact version:**
https://github.com/primefaces/primereact/blob/b0de52a67e2ad2bae9efc3a0101423db16ec3622/src/components/datatable/DataTable.js#L701

**Comment by Liam-OShea** [comment]
I am also experiencing this issue, additionally the null values appear to break the sort so that even without the null values the rows are out of order. The issue is resolved if sortMode=multiple is removed. 

Additionally, should null values be sorted to the bottom of the table, regardless of asc or desc sort order?

![NullMultipleSort](https://user-images.githubusercontent.com/28987268/124474244-b3f52900-dd76-11eb-9267-b8d18c8f2c57.PNG)

**Comment by Liam-OShea** [comment]
Please note this issue can be fixed by applying a sort function rather than using the table's default sort function. I used this one from a previous issue: 

https://github.com/primefaces/primereact/issues/348

However I am not sure how to import Objectutils. I ended up copying and pasting the resolveFieldData and isFunction methods.

**Comment by ursfan** [comment]
Unfortunately this issue wasn't fixed yet. In my opinion the implementation of the datatable sortfunction for single and multiple sort should handling the null values in the same way. Currently the null values are only handled correctly for "sortSingle", but not for "sortMultiple". In the sort function for the case of multiple columns selected in the datatable null values are handled as integer values.

The code is as follows in the function "multisortField":
if (typeof value1 === 'string' || value1 instanceof String) {
  if (value1.localeCompare && value1 !== value2) {
    return multiSortMeta[index].order * value1.localeCompare(value2, undefined, {
      numeric: true
    });
  }
} else {
  result = value1 < value2 ? -1 : 1;
}

while the sortSingle is implemented as:
 if (value1 == null && value2 != null) result = -1;else if (value1 != null && value2 == null) result = 1;else if (value1 == null && value2 == null) result = 0;else if (typeof value1 === 'string' && typeof value2 === 'string') result = value1.localeCompare(value2, undefined, {
              numeric: true
});else result = value1 < value2 ? -1 : value1 > value2 ? 1 : 0;

**Comment by melloware** [comment]
PR Submitted
