### ISSUE TITLE
DataTable: custom filter icon is not updating

### ISSUE THREAD

**Issue by lohani-harsha** [primefaces/primereact#2976]
### Describe the bug

Filter Icon button color is not changing when custom filter is applied, to show filter has been applied. It changes automatically in case of default filters.

### Reproducer

https://codesandbox.io/s/loving-bush-5gr5y4?file=/src/demo

### PrimeReact version

8.1.1

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. On name column click filter icon
2. Filter window opens. From second dropdown select custom filter (My Filter)
3. Click on apply button.
4. Color didn't change. (Refer below image)
<img width="74" alt="icon" src="https://user-images.githubusercontent.com/98345074/172651910-5cef961a-0ce4-471d-ae12-30d4bb427d1d.PNG">

### Expected behavior

Color should have been changed (light blue color refer below image) as it changes when default filters are applied.
![image](https://user-images.githubusercontent.com/98345074/172652327-ace6f8ed-557b-491e-a088-6219783d1fa2.png)

**Comment by GPetrites** [comment]
I'm having the same issue.  I can't figure out why, but the "p-column-filter-menu-button-active" class is not getting added to the button tag.

The issue appears to be with the filter and onFilter properties on the DataTable itself.  The only way I can get the indicator to work is by passing in a filters={filters} but NOT an onFilter={(e) => setFilters(e.filters)}

I stripped out a lot of unnecessary stuff from the sample to try to replicate.  As it stands, it's a strange hybrid of controlled (settings filters) and uncontrolled (missing onFilter to update the React state).  This hybrid works, but it's the only hybrid that appears to work.

If you comment out "filters" on line 83 the indicator stops working.

If you uncomment both lines 83 and 84 (filters and onFilter), the indicator also stops working.

Additionally, if you use the hybrid of filters but not onFilter but you do not initialize the filter object by commenting out line 31, the indicator also stops working.

Summary, the only combination in which the indicator works is:
- Create a filters object with default filters
- set filters on the dataTable to use the filters object
- do NOT use onFilter to update the object

https://codesandbox.io/s/winter-sun-s3mddf?file=/src/demo/DataTableFilterDemo.js

**Comment by omansak** [comment]
Yes,  I guess its bug

Problem in there

https://github.com/primefaces/primereact/blob/46e5ae66d656971f4c538e4a22d3d0a9dc9cd3b4/components/lib/datatable/ColumnFilter.js#L35

They sets `p-column-filter-menu-button-active` class if current filterState has difference old state. Your code always updates filterState so does not set highlights

solution :
check ` filterModel.value` is not null

**Comment by melloware** [comment]
@omansak care to submit a PR?

**Comment by melloware** [comment]
I fixed it with my PR.

**Comment by jnlinn** [comment]
Unfortunately this issue is not fixed. Just tried PrimeReact 8.4.0 but datatable filter icon not highlighting when filter value selected.

Filter icon highlighting functions correctly for hooks but not class component.

We are stuck using PrimeReact 7.2.1 until this issue is fixed since we have many class datatable components.

Can this issue be looked into again?

**Comment by melloware** [comment]
hmm its working for me.  Can you provide a code sandbox reproducer showing its not working on 8.4.0 please?

**Comment by melloware** [comment]
Oh I see try this sandbox on 8.4.0: https://codesandbox.io/s/loving-bush-5gr5y4?file=/src/demo

it works if you pick My Custom and enter a value in the text box.  But if you don't enter a value in the text box the filter thinks its not filtering anything.  So as long a a filter HAS a value it highlights.

**Comment by jnlinn** [comment]
The sandbox you provided is using hooks which we agree does work. The issue occurs when using class, e.g., 

class Customers extends React.Component  {
....
}

Can you provide a sandbox that uses class?

**Comment by melloware** [comment]
OK so you are still on 7.X branch which is no longer being patched.    The only way you will receive support on 7.X i assume is through PRO support:

**Comment by jnlinn** [comment]
To clarify, the issue of the filter icon highlight is in 8.X. The filter is not highlighting when a value is selected for datatable class components. This is why we are stuck on 7.X until it is fixed in 8.X.

Are you able to provide a sandbox of a datatable class component with filters using 8.X?

**Comment by melloware** [comment]
no but if you can provide a working sandbox showing the issue I can look at it

**Comment by brunoccst** [comment]
The issue with the `onFilter` is still happening.
When `onFilter` is set in the datatable, the `p-column-filter-menu-button-active` class is not applied to the filter icon.

I forked the sandbox mentioned above and created a second datatable in it, almost identical to the first datatable, except that it sets the `onFilter` function.
Check it out: https://codesandbox.io/s/custom-on-filter-not-applying-active-state-on-icon-fdrgr8

The filter icon on the first datatable has its color changed to blue, showing that it's active:
![image](https://user-images.githubusercontent.com/13342183/188917818-b2190945-462b-42b5-9044-c3f36b11aba8.png)

But the second datatable doesn't change at all:
![image](https://user-images.githubusercontent.com/13342183/188917834-3d16922c-2af3-4110-ab04-570ff5b40bdc.png)

**Comment by melloware** [comment]
feel free to submit a PR for review

**Comment by t-works** [comment]
According to my research when you use datable in controlled mode (assign and update filter manually) the filterModel.constraints and  filterStoreModel.constraints are identical.

I didn't test it but it seems th reason may be in  https://github.com/primefaces/primereact/blob/master/components/lib/datatable/ColumnFilter.js line 37. There is a check hasFIlter:

    const hasFilter = () => {
        if (!filterStoreModel || !filterModel) return false;
        return filterStoreModel.operator
            ? !isFilterBlank(filterModel.constraints[0].value) && filterStoreModel.constraints[0].value !== filterModel.constraints[0].value
            : !isFilterBlank(filterModel.value) && filterStoreModel.value !== filterModel.value;
    };

**Comment by jnlinn** [comment]
That's great information. Any ideas how to add a "work around" so the filter icon will highlight? Below is sample code of how we use datatable in control mode:

`constructor(props)` {
...
this.doFetchCustomersThrottled = _.debounce(this.doFetchCustomers, 300);
...
}

`onFilter = (event) =>` {

saveToSS(CUSTOMER_TABLE_FILTERS, event.filters);
this.setState({
filters: event.filters,
customerNumberSearch: event?.filters?.number?.value,
customerNameSearch: event?.filters?.name?.value,
customerLocationSearch: event?.filters?.location?.value,
customerContactSearch: event?.filters?.contact?.value,
selectedCustomerTypes: event?.filters?.cusType?.value || [],
selectedReferralTypes: event?.filters?.referral?.value || [],
selectedSalesReps: event?.filters?.salesRep?.value || [],
}, callback () => this.doFetchCustomersThrottled(this.props.pagination, this.props.sorting));

}

`return` (

`<DataTable>`
...
**onFilter={this.onFilter}**
...
`</DataTable>`

)

**Comment by t-works** [comment]
Unfortunately I don't know any way to make a workaround :(, AFAIK filterStoreModel is managed internally by DataTable.
We have been searching for a solution ourselves with no luck.
@melloware maybe you can shed some light on why hasFIlter can not have just:
const hasFilter = () => { if (!filterStoreModel || !filterModel) return false; return filterStoreModel.operator ? !isFilterBlank(filterModel.constraints[0].value) : !isFilterBlank(filterModel.value) ; };

without check:
filterStoreModel.constraints[0].value !== filterModel.constraints[0].value
?
Or how can we have the icon highlighted in controlled mode?
I suppose there is a reason why this additional check is there, that I can't see ...

Thank you.

**Comment by bhkangw** [comment]
+1 encountering this bug myself. Hoping for a fix

**Comment by melloware** [comment]
I am not quite sure why it behaves that way.  I suggest if you guys need more support to look into PRO support I am just an open source volunteer.

**Comment by jnlinn** [comment]
Should I submit a "new issue" here on GitHub for a bug fix and reference #3052?

**Comment by t-works** [comment]
Hi Melloware,
I can submit PR with this change

const hasFilter = () => { if (!filterStoreModel || !filterModel) return
false; return filterStoreModel.operator ?
!isFilterBlank(filterModel.constraints[0].value) :
!isFilterBlank(filterModel.value) ; };


I just hoped someone who put the additional checks can explain why these
were necessary. Maybe removing can cause other issues ...

wt., 20 wrz 2022, 15:21 użytkownik Bella FSM ***@***.***>
napisał:

**Comment by melloware** [comment]
sure!

**Comment by melloware** [comment]
@t-works Ahh OK the difference is between `filterDisplay="menu"` and `filterDisplay="row"` type filters.

The menus are different types of collections that is why it checks `constraints[0]` see the two types of arrays of filters here:

```js
	const menuFilters = {
		vin: { operator: FilterOperator.OR, constraints: [{ value: '', matchMode: FilterMatchMode.CONTAINS }] },
		make: { operator: FilterOperator.OR, constraints: [{ value: '', matchMode: FilterMatchMode.CONTAINS }] },
		model: { operator: FilterOperator.AND, constraints: [{ value: '', matchMode: FilterMatchMode.CONTAINS }] },
		color: { operator: FilterOperator.OR, constraints: [{ value: '', matchMode: FilterMatchMode.CONTAINS }] },
		year: { operator: FilterOperator.OR, constraints: [{ value: '', matchMode: FilterMatchMode.GREATER_THAN_OR_EQUAL_TO }] },
		modifiedTime: { operator: FilterOperator.OR, constraints: [{ value: '', matchMode: FilterMatchMode.DATE_AFTER }] }
	};

	const rowFilters = {
		vin: { value: '', matchMode: FilterMatchMode.CONTAINS },
		make: { value: '', matchMode: FilterMatchMode.CONTAINS },
		model: { value: '', matchMode: FilterMatchMode.CONTAINS },
		color: { value: '', matchMode: FilterMatchMode.CONTAINS },
		year: { value: '', matchMode: FilterMatchMode.GREATER_THAN_OR_EQUAL_TO },
		modifiedTime: { value: '', matchMode: FilterMatchMode.DATE_AFTER }
	};
```

**Comment by melloware** [comment]
Lets open a new ticket for this...

**Comment by melloware** [comment]
I opened: https://github.com/primefaces/primereact/issues/3373

**Comment by gem-hiteshahuja** [comment]
@melloware Hey I am facing the same issue with the latest version i.e. 8.6.1.
Issue :
I am using onFilter event for filtering to catch the filters object after filtering is done . But this is not updating the filter icon to active/not adding any active class.

Can you please confirm if this issue is resolved from your side? If yes, can you please confirm the released version for this?

**Comment by bhkangw** [comment]
@gem-hiteshahuja I believe it is set to release in [8.6.2](https://github.com/primefaces/primereact/milestone/102) - not sure about release date though

**Comment by LuizFellype** [comment]
version 10.9.7 stil has the same issue, if I pass onFilter, the button is not gettting active.

I am also seing this error sometimes when clearing the filter: 

<img width="484" height="342" alt="Image" src="https://github.com/user-attachments/assets/354dae5a-d9ce-420c-a417-69dbc85a8f56" />
