### ISSUE TITLE
MultiSelect: not selecting correct value when "options" objects contain property "value"

### ISSUE THREAD

**Issue by erik-vanlankvelt** [primefaces/primereact#3392]
**Describe the Bug**
I am not seeing selected "values" as checked in the dropdown.  When checkboxes are checked, incorrect value is returned when "onChange" is invoked.  "options" objects passed in contain a property/key named "value".

**Reproducer**
https://codesandbox.io/s/kind-bouman-2wobns?file=/src/App.tsx

**PrimeReact version**
8.5.0

**React version**
17.x

**Language**
React/TypeScript

**Build / Runtime**
Storybook

**Browser(s)**
Chrome

**Steps to reproduce the behavior**
- Using above link to reproduce, expand dropdown.  Notice that none of the checkboxes are checked.
- Select an item in the dropdown.  Notice that what's populated as a selection in the input is incorrect.

**Steps to reproduce correct behavior**
- Uncomment out `const [value, setValue] = useState(defaultValueGood)`;
- Comment out `const [value, setValue] = useState(defaultValueBad)`;
- Uncomment out `const optionLabel = "name"`;
- Comment out `const optionLabel = "label"`;
- Uncomment out `options={optionsGood}`;
- Comment out `options={optionsBad}`;
- Refresh

![Screen Shot 2022-09-29 at 12 58 23 PM](https://user-images.githubusercontent.com/873400/193122051-813345bf-fd46-44db-ad16-0cb56b3b85a5.png)
![Screen Shot 2022-09-29 at 12 58 11 PM](https://user-images.githubusercontent.com/873400/193122049-2c6fe4a8-7b3f-460c-bfd6-55fa2873287f.png)

**Comment by melloware** [comment]
Fixed your sandbox you were setting default values incorrectly: https://codesandbox.io/s/mystifying-einstein-9bezvf?file=/src/App.tsx

**Comment by erik-vanlankvelt** [comment]
@melloware I appreciate you fixing my sandbox, apologies for that.  This is still an issue however.

**Comment by erik-vanlankvelt** [comment]
@melloware should I not be using `selectedItemTemplate`?  I see what your change did, however, it won't work if there isn't a key of `value` in the options.  Is there some way to specify what the key should be in the options object for the value or do I have to use the key `value`?

**Comment by melloware** [comment]
Fixed your sandbox again to use `selectedItemTemplate` https://codesandbox.io/s/mystifying-einstein-9bezvf?file=/src/App.tsx

**Comment by erik-vanlankvelt** [comment]
Thanks @melloware.  Based on all the updates you've made in sandbox, it looks like the `options` object needs a `value` key every time.  Would you please confirm if this is the case or not?  See examples below.  I appreciate you taking the time to review this.

For example:

This works
```
const optionsBad = [
  {
    label: "Enamel pin letterpress",
    value: 1
  },
  {
    label: "Farm-to-table man bun",
    value: 2
  },
  {
    label: "Plaid locavore typewriter",
    value: 3
  }
];
```

This will never work:
```
const optionsBad = [
  {
    label: "Enamel pin letterpress",
    id: 1
  },
  {
    label: "Farm-to-table man bun",
    id: 2
  },
  {
    label: "Plaid locavore typewriter",
    id: 3
  }
];
```

**Comment by melloware** [comment]
That will work just fine you just need to use 'optionValue="id"' to tell it to use the aid field instead of default value field.

**Comment by erik-vanlankvelt** [comment]
@melloware I see, thanks!  So it really boils down to the format of the `value` prop.  It can't be an array of objects.

**Comment by melloware** [comment]
I don't understand?  Your use case makes no sense?  

Can you update your code sandbox to show what you are actually trying to do?

You want the value to be instead of a single number and array of numbers?

**Comment by erik-vanlankvelt** [comment]
Here is my use case that works: https://codesandbox.io/s/friendly-bardeen-14m1u5?file=/src/App.tsx.

Here is my use case that doesn't: https://codesandbox.io/s/hidden-field-p7ivin?file=/src/App.tsx.

I think it is related to [this line](https://github.com/primefaces/primereact/blob/master/components/lib/multiselect/MultiSelect.js#L394), where if the option has a `value` key, then it uses that instead of the whole option object.

Sorry for the confusion.

**Comment by melloware** [comment]
Yes but in your example that doesn't work you are not using "optionValue="id" to tell it to use the Id value as your option?

**Comment by erik-vanlankvelt** [comment]
In the example that doesn't work https://codesandbox.io/s/hidden-field-p7ivin?file=/src/App.tsx, setting `optionValue="id"` doesn't work and neither does `optionValue="value"`.

**Comment by melloware** [comment]
Ok let me take a look. I think I see what you are saying.

**Comment by erik-vanlankvelt** [comment]
@melloware just checking in, any updates?  Should I submit a PR?

**Comment by erik-vanlankvelt** [comment]
@melloware [PR](https://github.com/primefaces/primereact/pull/3462) submitted

**Comment by erik-vanlankvelt** [comment]
@melloware @mertsincan any chance this can be added to the next release?

**Comment by melloware** [comment]
I was waiting for PrimeTek to review before merging.

**Comment by erik-vanlankvelt** [comment]
Awesome, thanks!  I wasn't sure what your process was, so just checking in.

**Comment by erik-vanlankvelt** [comment]
@mertsincan is there any particular reason why this is not being included in releases?  I can't use this project without this change being released and may have to use a different library if this isn't going to be released soon.  Thanks

**Comment by erik-vanlankvelt** [comment]
@melloware I mucked up the git history so created a new PR for this that's clean.  I'm sorry for the inconvenience.
https://github.com/primefaces/primereact/pull/3613

**Comment by melloware** [comment]
Thanks for the PR!  Merged.
