### ISSUE TITLE
DataTable: TypeScript onSelectionChange error

### ISSUE THREAD

**Issue by CRC32EX** [primefaces/primereact#3998]
### Describe the bug

This error happen when i m coding on `Visual Studio Code`
StackBlitz is no error.
I don't know why.

![image](https://user-images.githubusercontent.com/25629617/215250492-b1b398b0-c61c-4a63-8140-bb40908d33cb.png)

### Reproducer

https://stackblitz.com/edit/vitejs-vite-f5j8ra?file=src%2FApp.tsx

### PrimeReact version

9.0.0-beta.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
Fixed by: https://github.com/primefaces/primereact/issues/3988

**Comment by dominikhiebler** [comment]
This is still a problem in 9.1.1. Updated example:
https://stackblitz.com/edit/vitejs-vite-q6iuda?file=src%2FApp.tsx

**Comment by melloware** [comment]
@dominikhiebler  I commented on 3988 for @bu3alwa
