### ISSUE TITLE
Paginator: onPageChange events fire twice with correct data and second one resetting it back.

### ISSUE THREAD

**Issue by GeorgSteyn** [primefaces/primereact#4101]
### Describe the bug

Hi guys, I am using the DataTable in Prime React Newest Version 9. When I use the paginator to move to another page which is not the first one the onPage callback gets fired twice. The first time it fires it has the correct behaviour moving to whatever page was selected and the second fire sets the table to the first page index. This happens as soon as the first prop changes on the DataTable. Has anyone encountered this issue? Tried this on version 8 also this morning. 

### PrimeReact version

9.2.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

**Comment by melloware** [comment]
Can you check if this is a duplicate of this: https://github.com/primefaces/primereact/issues/4095 ?

**Comment by GeorgSteyn** [comment]
The behaviour around what happens on the callbacks fire is the same. But the way the issue is triggered is different.

Below are the props we send to the table. When I remove the first prop. The table updates with its data as it should but obviously the paginator are still showing as if it is on page 1.

I also tested this with the normal Paginator and the same issue is happening there. Excluding the table from the problem.

```jsx
      <DataTable
        style={{
          display: 'flex',
          flexDirection: 'column',
          width: '100%',
          height: '65vh',
          overflow: 'auto',
        }}
        responsiveLayout="scroll"
        value={data}
        loading={loading}
        paginatorPosition="bottom"
        size="small"
        dataKey="id"
        paginator
        lazy
        rows={lazyState.rows}
        totalRecords={totalRecords}
        rowsPerPageOptions={[5, 10, 25, 50]}
        first={first}
        onPage={(event) => {
          console.log('DataTable TEst');
          onPage(event);
        }}
      >
```

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact/issues/4095

**Comment by GeorgSteyn** [comment]
@mertsincan Unfortunately this fix did not fix our bug could you re-open this issue please?

**Comment by mertsincan** [comment]
Hi @GeorgSteyn,

Could you please attach a codesandbox link for us to replicate? Also, what steps should we follow to see this problem in the attached sample?

Best Regards,

**Comment by melloware** [comment]
@GeorgSteyn will close until you provide a reproducer.

**Comment by JurieSpies** [comment]
The event now only runs once, but I understand what @GeorgSteyn means. To demonstrate the current issue, I've created a sandbox for previewing the problem. You can find it at: [https://codesandbox.io/s/jurie-prime-react-table-vksue4?file=/src/App.js].

Inside the **onPage** function, you will notice that it displays page 1 even though we are on page 2. Similarly, the event.first value shows 10 instead of 20.

![image](https://github.com/primefaces/primereact/assets/28508616/d8c2c1d5-6239-47e8-b611-314de89b72d9)

**Comment by melloware** [comment]
@JurieSpies do you mind opening a new issue as its slightly different than this original closed issue?

**Comment by anicarrr** [comment]
it seems that onPage callback makes the paginator to switch to be manual controlled but there's no way to set the current index 🤷🏻‍♂️
