### ISSUE TITLE
VirtualScroller: autoHighlight doesn't work

### ISSUE THREAD

**Issue by AvadhananamVamsiKrishna** [primefaces/primereact#4219]
### Describe the bug

When I use autoHighlight  in AutoComplete which has virtualScrollerOptions, It doesn't work. The first item in the list is not getting highlighted. When I removed the virtualScrollerOptions property then autoHighlight  was working properly.

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-d0w3y5?file=/src/App.js

### PrimeReact version

^9.2.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open this PrimeReact Autocomplete official basic demo code sandbox link: [https://codesandbox.io/s/eyny49](https://codesandbox.io/s/eyny49)
2. Add the below attributes to the autocomplete:
- autoHighlight={true}
- virtualScrollerOptions={{ itemSize: 38 }}
3. Just save and refresh the output window
4. You will be able to see the option doesn't get highlighted

### Expected behavior

The first item in the dropdown list should get highlighted when we use autoHighlight  with virtualScrollerOptions in Autocomplete

**Comment by melloware** [comment]
Hmm this was fixed previously so something has changed: https://github.com/primefaces/primereact/issues/2891

**Comment by vamsiravada** [comment]
May I know when this will be fixed?

**Comment by melloware** [comment]
@vamsiravada unless a community member donates a PR.  

Or if you have PRO support you can request this be fixed through your PRO account.

**Comment by melloware** [comment]
I am pretty sure #4536 fixed this by @userkks

**Comment by vamsiravada** [comment]
It's still reproducing @melloware

**Comment by melloware** [comment]
Yes the Milestone on the right says "10.0.0" which is not released yet. So this bug is fixed but not published.

**Comment by Frdnspnzr** [comment]
This still doesn't work in 10.0.2. See this example I forked from the Virtual Scroll example in the documentation and just added `autoHighlight`: https://stackblitz.com/edit/react-jqhgpu?file=src%2FApp.js

**Comment by melloware** [comment]
I didn't fix it but I did stop the crashing that it couldn't find `element.current` but the core issue still remains

**Comment by userkks** [comment]
@melloware checking on it

**Comment by sasa0103** [comment]
Anything new here?

**Comment by melloware** [comment]
@sasa0103 if you need immediate support I suggest you look into PrimeReact PRO Support: https://primereact.org/support/

**Comment by Frdnspnzr** [comment]
I just tried it again and it's working again since at least 10.6.3.
