### ISSUE TITLE
InputTextarea: Scrollbar jumping to the top when deleting last lines of long text in autoResize mode

### ISSUE THREAD

**Issue by tasirus** [primefaces/primereact#4346]
### Describe the bug

There is a problem with a scrollbar (of external component/page) jumping when deleting the last line or few last lines of really long text in InputTextarea. It happens when autoResize mode is on. We use the component with texts of max 64K characters, but the problem is visible even with smaller numbers like 10K (such text is used in CodeSandbox demo). I used CodeSandbox demo to show how the issue looks like, but I think it might be even better if you try to recreate the issue with InputTextarea component demo on primereact.org - described in **Steps to reproduce the behavior** section

### Reproducer

https://codesandbox.io/s/primereact-test-forked-oxndqe

### PrimeReact version

9.3.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

CodeSandbox demo:
1. scroll to the bottom of a page
2. delete the last line (or last few lines) of text inside InputTextarea
3. scrollbar is moved

InputTextarea component demo on [primereact.org](https://primereact.org/inputtextarea/#autoresize):
1. go to Auto Resize section
2. paste some long text inside InputTextarea
3. scroll down a bit so the end of input is in the middle of the screen
4. delete the last line or last few lines

https://user-images.githubusercontent.com/24657223/236424215-3f7faa15-ef44-4d4b-86f3-89aea97f040d.mov

### Expected behavior

Scroll is not moved as happens with shorter texts

**Comment by melloware** [comment]
Looks like this cause is this.  Changing the CSS of the InputTextArea must force the browser to move the scrollbar.

```js
        const resize = (initial) => {
            const inputEl = elementRef.current;

            if (inputEl && DomHandler.isVisible(inputEl)) {
                if (!cachedScrollHeight.current) {
                    cachedScrollHeight.current = inputEl.scrollHeight;
                    inputEl.style.overflow = 'hidden';
                }

                if (cachedScrollHeight.current !== inputEl.scrollHeight || initial) {
                    inputEl.style.height = '';
                    inputEl.style.height = inputEl.scrollHeight + 'px';

                    if (parseFloat(inputEl.style.height) >= parseFloat(inputEl.style.maxHeight)) {
                        inputEl.style.overflowY = 'scroll';
                        inputEl.style.height = inputEl.style.maxHeight;
                    } else {
                        inputEl.style.overflow = 'hidden';
                    }

                    cachedScrollHeight.current = inputEl.scrollHeight;
                }
            }
        };
```

**Comment by tasirus** [comment]
@melloware thanks for looking into the problem. Can it be fixed in the near future?

**Comment by melloware** [comment]
This one might be above me to fix as that resize code is intentional and the browser is reacting to that resize.

**Comment by userkks** [comment]
I just checked the issue is not reproducing, can you please check @tasirus @melloware , maybe got fixed with latest update.

**Comment by melloware** [comment]
I just tried it with 9.6.0 and its still happening for me in the Sandbox provided above?

**Comment by userkks** [comment]
Not in sandbox, I tried in the live documentation page.

**Comment by melloware** [comment]
It might not be quite the same. Also check strict mode vs non strict mode?
