### ISSUE TITLE
MenuBar: Submenu doesn't close on outside click when rendered inside <StrictMode>

### ISSUE THREAD

**Issue by genesisrhapsodos98** [primefaces/primereact#4614]
### Describe the bug

When rendered inside <React.StrictMode>, submenus within a MenuBar don't close when user clicks outside the menu.
This behavior doesn't happen when used without <React.StrictMode> (and is the expected behavior as seen on [the official website](https://primereact.org/menubar/))

### Reproducer

https://codesandbox.io/s/primereact-test-forked-zw2zsq

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Click on any menu that contains a submenu (e.g. File)
2. Move cursor to blank area of the page
3. Click on blank area

### Expected behavior

The submenu should close after step 3, but it stays open. I have to manually click on the parent MenuItem to make it close.

**Comment by melloware** [comment]
Thanks is fixed for 9.6.1

**Comment by abardik** [comment]
@melloware I use 9.6.2 installed from npm for Next.js project. I don't use <React.StrictMode>, but the issue still exists because since Next.js 13.4 strict mode is true by default with App Router. Setting reactStrictMode: false in next.config.js fixes the issue.

**Comment by melloware** [comment]
Nice. It's fixed for real in 10.0 when it comes out.
