### ISSUE TITLE
MultiSelect: on clicking inside checkbox to uncheck dropdown closes and maxLength and max not working

### ISSUE THREAD

**Issue by abdulbasit159** [primefaces/primereact#4728]
### Describe the bug

 on clicking inside the checkbox to uncheck selected value dropdown closes and maxLength and max not working

### PrimeReact version

9.6.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

**Comment by 1p0d** [comment]
Got the same problem with the dropdown getting closed on unchecking a checkbox directly in a TreeSelect with selectionMode checkbox. The dropdown does not close if you select an element by not clicking directly on the checkbox. The expected behavior would be that the dropdown does not close on clicking the checkbox since users probably want to select further things in a multi (tree) select. This expected behavior can be found back in v8.7

**Comment by melloware** [comment]
I need Code Sandbox reproducers for all these issues to see them in action.

**Comment by melloware** [comment]
You can use this one to start with and edit it to show the bug: https://stackblitz.com/edit/react-duwxzn?file=src%2FApp.js

**Comment by 1p0d** [comment]
> You can use this one to start with and edit it to show the bug: https://stackblitz.com/edit/react-duwxzn?file=src%2FApp.js

The described behavior shows in your sandbox already. Unchecking an element by clicking on the checkmark closes the dropdown, clicking on an elements text does not. The latter is what I would expect when clicking on the checkbox as well.

**Comment by melloware** [comment]
Yep I already fixed that in `master` both issues. SVG icons had an issue: https://github.com/primefaces/primereact/issues/4662

**Comment by jerlam06** [comment]
@melloware I can confirm that the issue is still there. Reproducible here: https://primereact.org/multiselect/
See: https://github.com/primefaces/primereact/issues/4523

**Comment by melloware** [comment]
Yep see the milestone on this ticket says it's slated for 10.0.0

**Comment by jerlam06** [comment]
@jerlam06 Ups my bad. Thanks :)
