### ISSUE TITLE
select components: props `appendTo` Incorrect first time mount

### ISSUE THREAD

**Issue by kl-nevermore** [primefaces/primereact#5311]
### Describe the bug

# when use `appendTo` ,the first time it was appended to the body, the second time it was mounted correctly
## CascadeSelect
![20231114155956_rec_](https://github.com/primefaces/primereact/assets/25167742/01566702-348a-42b7-8844-a06fcc52cc24)

## MultiSelect
![20231114160553_rec_](https://github.com/primefaces/primereact/assets/25167742/582e429f-8883-4358-81c0-5d22f4ffda4a)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-tk9y7q?file=/src/D.js:53-59

### PrimeReact version

10.0.9 and the master branch code

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 118

### Expected behavior
If appendTo is an HTML element, should it be used for calculation?( like MultiSelect ? )
or
mounted correctly, the position does not change(like antd)

_No response_

**Comment by melloware** [comment]
@kl-nevermore please try 10.1.0 and confirm your issue is fixed.

**Comment by kl-nevermore** [comment]
> @kl-nevermore please try 10.1.0 and confirm your issue is fixed.

sorry! I just saw this message!
I'll test it when I get finish work

**Comment by kl-nevermore** [comment]
https://codesandbox.io/p/sandbox/primereact-demo-forked-wn2yc7
@melloware 
this problem still exists

**Comment by melloware** [comment]
Can you investigate?

What I fixed was in `useMounteffect` I set the overlay.

```js
        useMountEffect(() => {
            alignOverlay();
        });

        const alignOverlay = () => {
            DomHandler.alignOverlay(overlayRef.current, labelRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
        };
```

So on Mount of the component the overlay should already be set to append to the correct spot where before it was waiting until it was shown the first time to appendTo?

**Comment by kl-nevermore** [comment]
if use ref or selectors ,the `appendTo` always is nil

There are two options
1: use state instead
```tsx
const ref = useRef();
const [refState, setRefState] = useState();
useEffect(() => {
  setRefState(ref.current);
}, []);
<MultiSelect appendTo={refState} />;
```
2: `appendTo` support function
```tsx
<MultiSelect appendTo={()=>ref.current} />;
```

**Comment by melloware** [comment]
I like solution 2 above.
