### ISSUE TITLE
TreeTable/Datatable: Calendar not showing correctly

### ISSUE THREAD

**Issue by prabhat0192** [primefaces/primereact#5529]
### Describe the bug

When Calendar is part of the input in Treetable or Datatable , it does not render at correct position which should be below or above the field based on the field location but it shows in the corner, when appendTo="self" is used it gets hidden behind the table.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-shxx68?file=%2Fsrc%2FApp.js%3A1%2C36

### PrimeReact version

10.x.x

### React version

17.x

### Language

ES6

### Build / Runtime

Create React App (CRA)

### Expected behavior

 it does not render at correct position which should be below or above the field based on the field location but it shows in the corner, when appendTo="self" is used it gets hidden behind the table.

**Comment by sarathkumarps17** [comment]
Can I work on this?

**Comment by melloware** [comment]
I don't see why not @sarathkumarps17

**Comment by prabhat0192** [comment]
@melloware is anyone working on this , or any workaround available?

**Comment by iemi111** [comment]
I've had the same issue and found that if you select a date on the calendar and then click again on the input field without losing focus, the calendar is rendered at the correct position.

https://codesandbox.io/p/sandbox/primereact-demo-forked-9c588l?file=%2Fsrc%2FApp.js%3A22%2C5

![calendar](https://github.com/primefaces/primereact/assets/35145977/e3ea5699-88fe-4a0b-a9b6-669ecf4adcd4)

**Comment by melloware** [comment]
This may actually be fixed by another fix @kl-nevermore just made yesterday.

**Comment by kl-nevermore** [comment]
There are other reasons for this issue. I looked at it yesterday and haven't found the reason yet

if use other component instead calendar this problem still exists

**Comment by kl-nevermore** [comment]
@melloware 
I found it. I'll see how he can fix it later.
![image](https://github.com/primefaces/primereact/assets/25167742/15551b89-8aa0-43dc-93a3-452357858831)

**Comment by kl-nevermore** [comment]
when use table edit, overlayRef.current is null, this code can work
Do you think it is a reasonable solution?
```tsx
useUpdateEffect(() => {
    if (overlayVisibleState || props.visible) {
        if (overlayRef.current === null) {
            setTimeout(() => {
                alignOverlay();
            });
        } else {
            alignOverlay();
        }
    }
}, [currentView, overlayVisibleState, props.visible]);
```

**Comment by melloware** [comment]
You could just simplify to...

```js
useUpdateEffect(() => {
    // #5529 fix
    if (overlayVisibleState || props.visible) {
            setTimeout(() => {
                alignOverlay();
            });
    }
}, [currentView, overlayVisibleState, props.visible]);
```

The setTimeout should not be a problem for either scenario I would think

**Comment by kl-nevermore** [comment]
@melloware 
this can fix iemi111's [demo](https://codesandbox.io/p/sandbox/primereact-demo-forked-9c588l?file=%2Fsrc%2FApp.js%3A22%2C5), can not fix this issue


If write like this, the OverlayPanel  not mount and op.current is null, so its not work
what do you think ?
```tsx
<TreeTable>
    <Column field="name" header="Name" expander={true}></Column>
      ...
    <OverlayPanel ref={op}>
        <Calendar />
    </OverlayPanel>
</TreeTable>;
```

**Comment by kl-nevermore** [comment]
This will be rendered as a column, I feel like this is a very special way of writing
If written this way it should work, should the calendar be displayed on the header after calling the show method?
```
<OverlayPanel ref={op}>
    <Calendar />
</OverlayPanel>
```
![image](https://github.com/primefaces/primereact/assets/25167742/c91092bb-9a0a-47f5-b441-6954b435c3c0)

**Comment by prabhat0192** [comment]
@kl-nevermore is there any workaround, or any way to pass value to that particular ref?

**Comment by kl-nevermore** [comment]
@prabhat0192 
If you expect the same as https://github.com/primefaces/primereact/issues/5529#issuecomment-1853772333, you can refer to that
