### ISSUE TITLE
MeterGroup: Component is not exported from the library

### ISSUE THREAD

**Issue by Yousef-Matar** [primefaces/primereact#6268]
### Describe the bug

Component cannot be used in projects, as it is not exported from the library.

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1 - Install primereact
2 - Try to import MeterGroup
Or
Open the component code on stackblitz

**Comment by melloware** [comment]
@gucal it looks like the other new components like IconGroup IconField have this same issue.

**Comment by gucal** [comment]
Thanks for the report. The problem has been fixed.

**Comment by cbutler90** [comment]
I am still having this issue with the new components (e.g. InputField, InputIcon)

**Comment by cbutler90** [comment]
I am still having this same issue regarding the new components (e.g. IconField, InputIcon, etc.)

**Comment by melloware** [comment]
The new version with the fix has not been released yet.
