### ISSUE TITLE
StepperPanel: New const instead of class components are no valid JSX.Element's

### ISSUE THREAD

**Issue by dvpritzbuer** [primefaces/primereact#6334]
### Describe the bug

"JSX element type 'Stepper' does not have any construct or call signatures."

"ERROR(TypeScript)  'StepperPanel' cannot be used as a JSX component.
  Its type 'Component<StepperPanelProps, any, any>' is not a valid JSX element type."

### Reproducer

https://stackblitz.com/edit/vitejs-vite-9mym3z?file=src%2FApp.tsx,package.json

### PrimeReact version

10.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

**Comment by melloware** [comment]
I think i fixed it with this: https://github.com/primefaces/primereact/pull/6325

**Comment by gucal** [comment]
Hi,

With release 10.6.3 the issue should be fixed. If you notice that the issue persists, please ping me.

**Comment by dvpritzbuer** [comment]
Problem is not solved yet, still the same error with 10.6.3.

I've updated the stackblitz: https://stackblitz.com/edit/vitejs-vite-9mym3z?file=src%2FApp.tsx

**Comment by dvpritzbuer** [comment]
What about this definition?
`export declare const Stepper: React.ForwardRefExoticComponent<StepperProps, any>;`
`export declare const StepperPanel: React.ForwardRefExoticComponent<StepperPanelProps, any>;`

This works locally for me and removes the errors

**Comment by dvpritzbuer** [comment]
What about the following type definition?
`declare const StepperPanel: React.FC<React.PropsWithChildren<StepperPanelProps>>;`

That works locally for me and should be a proper type.

**Comment by melloware** [comment]
@dvpritzbuer do you want to submit a PR by any chance?

**Comment by dvpritzbuer** [comment]
@melloware yes, I can do that

**Comment by melloware** [comment]
OK i assigned to you!

**Comment by dvpritzbuer** [comment]
@melloware 
Can't push my branch "issue-6334" with "remote: Permission to primefaces/primereact.git denied to dvpritzbuer."
Is it on my side or do you need to give me permissions?

**Comment by melloware** [comment]
Yeah on GitHub you can only create PR's from a fork: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
