### ISSUE TITLE
Z index is increasing on every close and open action for Dialog component

### ISSUE THREAD

**Issue by nileshzala005** [primefaces/primereact#7041]
### Describe the bug

Dialog component increasing z-index by 1 on every close and open action. this issue stopped other components(e.g. dropdown list item) from rendering inside the dialog component.
<img width="1676" alt="Z-index" src="https://github.com/user-attachments/assets/c26e3ab8-3b72-4f4d-b88a-7b00c25419b5">

### Reproducer

https://stackblitz.com/edit/bp4c3k?file=src%2FApp.jsx

### System Information

"primereact": "^10.8.2",

### Steps to reproduce the behavior

1. Click on the Show button on the above demo project
2. Open the developer tool and see the z-index of dialog HTML code, it's increasing on every close and open dialog action

### Expected behavior

z-index of dialog HTML code should not increase by 1 on every close and open action

**Comment by melloware** [comment]
This is by design as every time the dialog opens it must be on top so its z-index is increased.  All the PrimeTek libs work the same way.

What is your real issue?

**Comment by nileshzala005** [comment]
@melloware When the z-index is more than 2103, it does not display dropdowns properly.  Please refer to this updated [demo](https://stackblitz.com/edit/bp4c3k?file=src%2Fnew-dialog.jsx) 
![image](https://github.com/user-attachments/assets/152f75ac-d8e9-49a0-858d-a820f70089d1)

Please provide a workaround for this and update the above demo.

**Comment by melloware** [comment]
cc @navedqb

**Comment by madalina-agh** [comment]
I'm facing the same issue. I guess that the way it was intended to work was to set the z-index just higher by 1 in relation to the current highest on the page. The actual implementation just keeps growing each Dialog opening by 1, reaching very high values if the page is not refreshed in a while.

**Comment by ozziej** [comment]
Can confirm that this is an issue with drop down items inside a dialog, I can easily reproduce. 
Z-index on dialog goes from 2302 -> 4604 but the dropdown stays at z-index of 1001 for the dropdown.

Classes that have the low z-index are : 
<div class="p-dropdown-panel p-component p-ripple-disabled p-connected-overlay-enter-done">

PrimeReact 10.8.3
![Screenshot 2024-10-07 at 14 01 50](https://github.com/user-attachments/assets/426fd7de-9b9e-4c77-a666-deb5f678be39)

**Comment by melloware** [comment]
Converted this issue to a BUG

**Comment by tanerengiiin** [comment]
It seems like this issue has been resolved in the latest version. Could you please confirm and provide more information if there are any updates? @nileshzala005

**Comment by melloware** [comment]
@tanerengiiin this is still happening.  What he is saying is the dialog keeps increasing its z-index but the dropdown component inside the dialog stays the same.

**Comment by tanerengiiin** [comment]
https://stackblitz.com/edit/w88qtr6z?file=src%2FApp.jsx

Could you please check it in this reproducer? Or did I not understand the issue? @melloware

**Comment by melloware** [comment]
Ahhh yes your reproducer is working their old one is on an older version of PrimeReact.  This can be closed.
