### ISSUE TITLE
InputMask: Unexpected behavior when using "unmask" property

### ISSUE THREAD

**Issue by kpe09** [primefaces/primereact#7755]
### Describe the bug

When using a mask that has spaces between the characters, e.g., "**** **** ****", and the "unmask" property is enabled, when you start entering characters their sequence becomes messed up at some point.

### Reproducer

https://stackblitz.com/edit/bdj2wmcv?file=src%2FApp.jsx

### System Information

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    primereact: latest => 10.9.2 
    react: 18.3.1 => 18.3.1
```

### Steps to reproduce the behavior

1. Enable "unmask" in InputMask component with mask "**** **** ****"
2. Enter sequence of characters: ABCDEFGHIJKL in InputMask
3. When entering F the sequence of the characters becomes misaligned (ABCDFE)

### Expected behavior

When entering a certain sequence of characters, the sequence should not be randomly misaligned.

**Comment by sarathkumarsasi** [comment]
Hi @melloware, Can I work on this?

**Comment by melloware** [comment]
Sure

**Comment by sarathkumarsasi** [comment]
Hi @melloware , I have pushed the fix. Please verify and merge.

**Comment by melloware** [comment]
I think this is already fixed by: https://github.com/primefaces/primereact/pull/7686  as in main I running `npm run dev` i cannot reproduce your issue.

**Comment by sarathkumarsasi** [comment]
> I think this is already fixed by: [#7686](https://github.com/primefaces/primereact/pull/7686) as in main I running `npm run dev` i cannot reproduce your issue.

https://stackblitz.com/edit/bdj2wmcv?file=src%2FApp.jsx
I am still getting the input jumbled up when the character reaches the space part in the given mask, so I guess the issue persists.
@melloware Please double-check it once more.

**Comment by melloware** [comment]
@sarathkumarsasi stackblitz is running PrimeReact 10.9.2 as 10.9.3 is not released yet. The fix is in current gitHub Main branch but not been released yet.

You can test it by running `npm run dev` and just editing the InputMask basicdoc.js page to match the StackBlitz. When I do that I can't reproduce the issue its working fine.

**Comment by melloware** [comment]
10.9.3 is out and you can see its fixed: https://stackblitz.com/edit/bdj2wmcv-tbhykha8?file=src%2FApp.jsx
